LOC FUNCTION : we use it for label or condition.(label/condition ke basis me hum loc use karte hai)

In [19]:
import pandas as pd

In [9]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],
    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

In [10]:
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

LOC FUNCTION: we use it for label or condition. loc/label

In [ ]:
df.loc[0] #specific row #index 0 vali row cahiye

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [12]:
df.loc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [13]:
df.loc[0,"Patient_ID"]#specific row and column

'P101'

In [14]:
df.loc[:,["Patient_ID","Surgery_Type"]] #for multiple column

  Patient_ID      Surgery_Type
0       P101   Cholecystectomy
1       P102              CABG
2       P103      Appendectomy
3       P104     Hernia Repair
4       P105  Knee Replacement
5       P106              PTCA
6       P107      Appendectomy
7       P108   Cholecystectomy
8       P109     Hernia Repair
9       P110  Knee Replacement

In [17]:
#loc with condition
#only wants hyderabad patients
df.loc[df["City"]=="Hyderabad"]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency
4,P105,41,Hyderabad,Knee Replacement,180,5,Planned
6,P107,29,Hyderabad,Appendectomy,70,1,Emergency
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned

In [ ]:
#only wants hyderabad patients, and print patient id , surgery type and admission type
df.loc[df["City"]=="Hyderabad"][["Patient_ID","Surgery_Type","Admission_Type"]]

  Patient_ID      Surgery_Type Admission_Type
0       P101   Cholecystectomy        Planned
2       P103      Appendectomy      Emergency
4       P105  Knee Replacement        Planned
6       P107      Appendectomy      Emergency
8       P109     Hernia Repair        Planned