ILOC FUNCTION:

In [1]:
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],
    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)

In [3]:
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

In [4]:
df.iloc[0] #index 0 ke puri chije aa rhi hai

Patient_ID                           P101
Age                                    45
City                            Hyderabad
Surgery_Type              Cholecystectomy
Operation_Duration_Min                 90
Length_of_Stay_Days                     2
Admission_Type                    Planned
Name: 0, dtype: object

In [5]:
df.iloc[1] # index 1 ki chije aa rhi hai (1st row index)

Patient_ID                     P102
Age                              62
City                       Warangal
Surgery_Type                   CABG
Operation_Duration_Min          240
Length_of_Stay_Days               7
Admission_Type            Emergency
Name: 1, dtype: object

In [6]:
df.iloc[0,0] #specific, rows and columns

'P101'

In [7]:
#first 3 rows
df.iloc[0:3]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
0,P101,45,Hyderabad,Cholecystectomy,90,2,Planned
1,P102,62,Warangal,CABG,240,7,Emergency
2,P103,34,Hyderabad,Appendectomy,75,1,Emergency

In [8]:
#first 3 row + first 3 columns
df.iloc[0 : 3, 0 : 3]

  Patient_ID  Age       City
0       P101   45  Hyderabad
1       P102   62   Warangal
2       P103   34  Hyderabad

In [9]:
#first 5 rows + first 5 column
df.iloc[0:5,0:5]

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180

Difference Between loc and iloc

In [ ]:
#index 2 wali patient ki complete information display
df.loc[2]

Patient_ID                        P103
Age                                 34
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              75
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 2, dtype: object

In [ ]:
#third patient ki complete information display cahiye (index starts with 0)
df.iloc[2]

Patient_ID                        P103
Age                                 34
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              75
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 2, dtype: object

In [ ]:
#what is the main difference between loc and iloc
#lable ----loc

#position index ---iloc

In [ ]:
#1)hospital wants to check the details of the 4th patient
df.iloc[3]

Patient_ID                         P104
Age                                  55
City                         Vijayawada
Surgery_Type              Hernia Repair
Operation_Duration_Min              110
Length_of_Stay_Days                   3
Admission_Type                  Planned
Name: 3, dtype: object

In [ ]:
#2)patient whoes index label is 7(loc)
df.loc[6]

Patient_ID                        P107
Age                                 29
City                         Hyderabad
Surgery_Type              Appendectomy
Operation_Duration_Min              70
Length_of_Stay_Days                  1
Admission_Type               Emergency
Name: 6, dtype: object

In [ ]:
#3)display the first 5 patients, show only --patient_id, city, age
df.loc[0:5][["Patient_ID","City","Age"]]

  Patient_ID        City  Age
0       P101   Hyderabad   45
1       P102    Warangal   62
2       P103   Hyderabad   34
3       P104  Vijayawada   55
4       P105   Hyderabad   41
5       P106   Nizamabad   68

In [ ]:
#4)last 3 patient data
df.iloc[-3:]

,Patient_ID,Age,City,Surgery_Type,Operation_Duration_Min,Length_of_Stay_Days,Admission_Type
7,P108,52,Warangal,Cholecystectomy,95,2,Planned
8,P109,47,Hyderabad,Hernia Repair,120,3,Planned
9,P110,73,Karimnagar,Knee Replacement,200,6,Planned

In [ ]:
#5)patient_id, city (loc)
df.loc[:,["Patient_ID","City"]] #sari row cahiye thi iss liye(:)use kiya, or 2 column cahiye the iss liye us ke 
#aage patient id or city likha

  Patient_ID        City
0       P101   Hyderabad
1       P102    Warangal
2       P103   Hyderabad
3       P104  Vijayawada
4       P105   Hyderabad
5       P106   Nizamabad
6       P107   Hyderabad
7       P108    Warangal
8       P109   Hyderabad
9       P110  Karimnagar

In [23]:
#6)find all patients from warangal dispaly patient_id, surgery, age
df.loc[df["City"]=="Warangal",["Patient_ID","Surgery_Type","Age","City"]]

  Patient_ID     Surgery_Type  Age      City
1       P102             CABG   62  Warangal
7       P108  Cholecystectomy   52  Warangal

In [24]:
#7)find patients whoes age is greater than 50. dispaly patient_id, age, city
df.loc[df["Age"]>50,["Patient_ID","Age","City"]]

  Patient_ID  Age        City
1       P102   62    Warangal
3       P104   55  Vijayawada
5       P106   68   Nizamabad
7       P108   52    Warangal
9       P110   73  Karimnagar

In [27]:
#8)rows 2 to 5, column 1 to 4
df.iloc[2:6, 1:5]

   Age        City      Surgery_Type  Operation_Duration_Min
2   34   Hyderabad      Appendectomy                      75
3   55  Vijayawada     Hernia Repair                     110
4   41   Hyderabad  Knee Replacement                     180
5   68   Nizamabad              PTCA                     150

In [ ]:
#9)Patient at index 4, patient_id, surgery_type (indexing starts from 0 in iloc)
df.iloc[4][["Patient_ID","Surgery_Type"]]

Patient_ID                  P105
Surgery_Type    Knee Replacement
Name: 4, dtype: object

In [ ]:
#challange: find the youngest emergency patient, display patient_id, age ,city
df.loc[df["Admission_Type"]=="Emergency","Age"].min()[["Patient_ID","Age","City"]]

IndexError: invalid index to scalar variable.