TOPICS:
         LOC and ILOC Practice

In [1]:
import pandas as pd

In [2]:

data = {
    "Student": ["Amit", "Neha", "Rahul", "Pooja"],
    "Marks": [85, 92, 76, 88],
    "City": ["Nagpur", "Pune", "Mumbai", "Nashik"]
}

df = pd.DataFrame(data, index=[101, 105, 110, 115])

In [3]:
print(df)

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [ ]:
#first 2 row
df.iloc[0:2] #iloc me indexing 0 se start hoti hai

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune

In [6]:
#position 1 se 3
df.iloc[1:4]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [7]:
#row and column slicing
df.iloc[0:2 , 0:2]

    Student  Marks
101    Amit     85
105    Neha     92

In [8]:
#last 2 row
df.iloc[2:4]

    Student  Marks    City
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [9]:
#first 3 rows
df.iloc[:3]

    Student  Marks    City
101    Amit     85  Nagpur
105    Neha     92    Pune
110   Rahul     76  Mumbai

In [10]:
#1 se leke sari rows
df.iloc[1:]

    Student  Marks    City
105    Neha     92    Pune
110   Rahul     76  Mumbai
115   Pooja     88  Nashik

In [12]:
#ek specific column ki first 3 values
df.iloc[:3,1] # : 3---first 3 rows, 1----column ki possition

101    85
105    92
110    76
Name: Marks, dtype: int64