In [1]:
import pandas as pd

In [2]:
data={
    "Name":["amit","riya","rahul","sneha","priya","vikas","neha","akash","pooja","rohan"],
    "Age":[20,21,22,20,23,21,22,20,21,23],
    "City":["nagpur","pune","mumbai","nagpur","pune","mumbai","nagpur","pune","nagpur","mumbai"],
    "Python_Marks":[85,92,76,88,95,67,81,73,90,78],
    "Sql_Marks":[80,89,72,91,94,65,79,70,88,77],
    "Attendance":[90,95,78,92,98,70,85,76,94,82]
}
df=pd.DataFrame(data)

In [3]:
print(df)

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
0   amit   20  nagpur            85         80          90
1   riya   21    pune            92         89          95
2  rahul   22  mumbai            76         72          78
3  sneha   20  nagpur            88         91          92
4  priya   23    pune            95         94          98
5  vikas   21  mumbai            67         65          70
6   neha   22  nagpur            81         79          85
7  akash   20    pune            73         70          76
8  pooja   21  nagpur            90         88          94
9  rohan   23  mumbai            78         77          82

In [4]:
print(df.head(4))

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
0   amit   20  nagpur            85         80          90
1   riya   21    pune            92         89          95
2  rahul   22  mumbai            76         72          78
3  sneha   20  nagpur            88         91          92

In [5]:
print(df.tail(3))

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
7  akash   20    pune            73         70          76
8  pooja   21  nagpur            90         88          94
9  rohan   23  mumbai            78         77          82

In [6]:
print(df.shape)

(10, 6)

In [7]:
print(df.columns)

Index(['Name', 'Age', 'City', 'Python_Marks', 'Sql_Marks', 'Attendance'], dtype='str')

In [8]:
print(df.dtypes)

Name              str
Age             int64
City              str
Python_Marks    int64
Sql_Marks       int64
Attendance      int64
dtype: object

In [9]:
print(df["Name"])

0     amit
1     riya
2    rahul
3    sneha
4    priya
5    vikas
6     neha
7    akash
8    pooja
9    rohan
Name: Name, dtype: str

for multiple columns access

In [ ]:
print(df[["Name","City","Python_Marks"]]) #it use to access multiple columns

    Name    City  Python_Marks
0   amit  nagpur            85
1   riya    pune            92
2  rahul  mumbai            76
3  sneha  nagpur            88
4  priya    pune            95
5  vikas  mumbai            67
6   neha  nagpur            81
7  akash    pune            73
8  pooja  nagpur            90
9  rohan  mumbai            78

In [ ]:
print(df[df["City"]=="pune"]) #only wants pune students

    Name  Age  City  Python_Marks  Sql_Marks  Attendance
1   riya   21  pune            92         89          95
4  priya   23  pune            95         94          98
7  akash   20  pune            73         70          76

In [13]:
print(df[df["Python_Marks"]>80])

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
0   amit   20  nagpur            85         80          90
1   riya   21    pune            92         89          95
3  sneha   20  nagpur            88         91          92
4  priya   23    pune            95         94          98
6   neha   22  nagpur            81         79          85
8  pooja   21  nagpur            90         88          94

In [24]:
print(df[(df["City"]=="nagpur") & (df["Python_Marks"]>80)])

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
0   amit   20  nagpur            85         80          90
3  sneha   20  nagpur            88         91          92
6   neha   22  nagpur            81         79          85
8  pooja   21  nagpur            90         88          94

#Advance Filter

#sort_vales #for data arrangements

In [ ]:
df.sort_values("Python_Marks") #arrange karta hai line se chote se bada

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
5  vikas   21  mumbai            67         65          70
7  akash   20    pune            73         70          76
2  rahul   22  mumbai            76         72          78
9  rohan   23  mumbai            78         77          82
6   neha   22  nagpur            81         79          85
0   amit   20  nagpur            85         80          90
3  sneha   20  nagpur            88         91          92
8  pooja   21  nagpur            90         88          94
1   riya   21    pune            92         89          95
4  priya   23    pune            95         94          98

In [26]:
df.sort_values("Python_Marks",ascending=False)# ye assending to descending karenga

    Name  Age    City  Python_Marks  Sql_Marks  Attendance
4  priya   23    pune            95         94          98
1   riya   21    pune            92         89          95
8  pooja   21  nagpur            90         88          94
3  sneha   20  nagpur            88         91          92
0   amit   20  nagpur            85         80          90
6   neha   22  nagpur            81         79          85
9  rohan   23  mumbai            78         77          82
2  rahul   22  mumbai            76         72          78
7  akash   20    pune            73         70          76
5  vikas   21  mumbai            67         65          70